#remote_theme: just-the-docs/just-the-docs
remote_theme: adamrehn/jekyll-theme-gitbook@v0.0.1
title: SloppyDocs
description: Sloppy Designs Documentation
baseurl: ""
color_scheme: sloppydesigns

# Aux links for the upper right navigation
aux_links:
  "Tebex":
    - "//www.sloppydesigns.com"
  "Discord":
    - "//discord.gg/Q88zQUUKxs"
  "YouTube":
    - "//youtube.com/channel/UC3t4WYhIvjhGXPNyv0Qh43g"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
