remote_theme: just-the-docs/just-the-docs

# Site settings
color_scheme: sloppydesigns
title: SloppyDesigns
email: sloppydesigns@outlook.com
description: Sloppy Designs Documentation
baseurl: ""
url: "https://docs.sloppydesigns.com"

# Aux links for the upper right navigation
aux_links:
  "Tebex Store":
    - "//www.sloppydesigns.com"
  "Discord":
    - "//discord.gg/sloppydesigns"
  "YouTube":
    - "//youtube.com/channel/UC3t4WYhIvjhGXPNyv0Qh43g"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  tests:
    permalink: "/docs/sd-cityservices/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    tests:
      # Give the collection a name
      name: Tests
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

search_enabled: false

search:
  button: false