remote_theme: just-the-docs/just-the-docs

# Site settings
color_scheme: sloppydesignsdark
title: SloppyDesigns
email: sloppydesigns@outlook.com
description: Sloppy Designs Documentation
baseurl: ""
url: "https://docs.sloppydesigns.com"

# Aux links for the upper right navigation
aux_links:
  "Tebex Store":
    - "//www.sloppydesigns.com"
  "Discord":
    - "//discord.gg/sloppydesigns"
  "YouTube":
    - "//youtube.com/channel/UC3t4WYhIvjhGXPNyv0Qh43g"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# For copy button on code
enable_copy_code_button: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search_enabled: false

search:
  button: false

collections:
  scripts:
    permalink: "/:collection/:path/"
    output: true
  free:
    permalink: "/:collection/:path/"
    output: true
  others:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    scripts:
      name: SCRIPTS
    free:
      name: FREE RELEASE
    others:
      name: OTHERS
    