remote_theme: just-the-docs/just-the-docs

# Site settings
color_scheme: sloppydesigns
title: SloppyDocs
email: sloppydesigns@outlook.com
description: Sloppy Designs Documentation
baseurl: ""
url: "https://docs.sloppydesigns.com"

# Aux links for the upper right navigation
aux_links:
  "Tebex":
    - "//www.sloppydesigns.com"
  "Discord":
    - "//discord.gg/Q88zQUUKxs"
  "YouTube":
    - "//youtube.com/channel/UC3t4WYhIvjhGXPNyv0Qh43g"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search_enabled: true

search:
  button: true